version: "{build}"
clone_depth: 1
clone_folder: c:\gopath\src\github.com\rhysd\gocaml
environment:
    GOPATH: c:\gopath
install:
    - echo %PATH%
    - echo %GOPATH%
    - go version
    - go env
    - go get -v -t -d ./ast ./closure ./mir ./syntax ./token ./sema ./common ./mono
    - go get golang.org/x/tools/cmd/goyacc
    - go get github.com/haya14busa/goverage
    - set PATH=%PATH%;%GOPATH%\bin
build: off
test_script:
    - goyacc -o syntax/grammar.go syntax/grammar.go.y
    - go test -v ./ast ./closure ./mir ./syntax ./token ./sema ./common ./mono
    - goverage -coverprofile=coverage.txt -covermode=count ./ast ./mir ./closure ./syntax ./token ./sema ./common ./mono
    - go tool cover -func coverage.txt
after_test:
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "coverage.txt"
deploy: off
