language: java
python:
  - "2.7"

os: linux
dist: bionic # 18.04

jobs:
  include:
  - os: linux
    env:
      - JDK="labsjdk-ce-11" GATE="build,debuginfotest" PRIMARY="substratevm"
    arch:
      - arm64
    addons:
      apt:
        packages:
          - gdb
  - os: linux
    arch: arm64
    env: JDK="labsjdk-ce-11" GATE="fullbuild,test:1:100" PRIMARY="compiler"
  - os: linux
    arch: arm64
    env: JDK="labsjdk-ce-11" GATE="build,test:0:1" PRIMARY="compiler"
  - os: linux
    arch: arm64
    env: JDK="labsjdk-ce-11" GATE="build,bootstraplite" PRIMARY="compiler"

install:
  - |
      export MX_PATH=${TRAVIS_BUILD_DIR}/../mx
      git clone --depth 1 https://github.com/graalvm/mx.git ${MX_PATH}
      export PATH=${PATH}:${MX_PATH}
  - |
      mx -y  --no-warning fetch-jdk --java-distribution ${JDK} --to ${TRAVIS_BUILD_DIR}/.. --alias jdk
      export JAVA_HOME=${TRAVIS_BUILD_DIR}/../jdk

script:
  - echo ${JAVA_HOME}
  - ${JAVA_HOME}/bin/java -version
  - |
      mx --primary-suite-path ${TRAVIS_BUILD_DIR}/${PRIMARY} --J @"-Xmx2g" --java-home=${JAVA_HOME} gate --strict-mode --tags ${GATE}
after_failure:
  - cat hs_err*
notifications:
  # Send a notification of a build failure on the master branch to
  # travis-ci channel in public GraalVM workspace
  slack:
    secure: RqC8efMebgYxxZeS63zTpNFIrJtgisOEjHNzlQBRDgIZ2JXcIoRL3xL6d3I+BoW8iGdOPJuNGC1WgDr8O4ZJOf5A32xZKpLU+aVR79Lq5LOezsoa8PCNXlZmxcc9oKFaM1a0cJGxLLg3F1wq9RUUHwfOMS8YuW7dmqFCtUOGmcIF1Rsal8vHyOqCYbiu7wxmUNmkqlJtXnztgQhLCGhd6ya0k6Dw8EVYoMWpHOTB6+9irNAp0BP0b1SvPQm9a5KzuASXSahapt/6CeCSrizN5RBKrMzVjcZhTarLm0Lt+3Ah7j1BQw2YBcDVYIEFUqABquXnuKb4+Hu6L8QRfmJzJ2w1cxC49WTEWWZu31gk2/0oSMsH58LovFG21ZHgQ/UZH1N7UYzS/rnHr2dzjZHaBIiWsRADoqSg9eNoz0ld2k8Up6k/T9YxUYN72+/TWKmRUDGF7gpkN097G1klaJb1MiLXDE5bvxbnH3+wVmfpzAVkE5Q0nfkZL53B5ymw1E8EtGvppcbnvHv0L3ccyRiX3iIgJcvINf+6sRXBqdB7HSZOEmRGiH7EsaUOdMxRhfLo1zA5xK+7k0fRBhViPJKEosflRkG7qhUNeqXDH6lrlCee5yqLoBsn0Xb6WDgCBQrVOSj2sHrvp0qO0UWKH8InDkhMPXddVq5RECnMjsusQ5g=
    if: branch = master AND repo = oracle/graal
    on_failure: always
    on_success: never
    on_pull_requests: false
