sudo: required

dist: trusty

os:
    - osx

services:
    - docker

language: bash

matrix:
  include:
    - os: osx
    # works on Precise and Trusty
    - os: linux
      env: CXX="g++" BUILD_ARCH="x86"
    
    - os: linux
      env: CXX="g++" BUILD_ARCH="x64"

    # works on Precise and Trusty
    - os: linux
      env: CXX="clang++" BUILD_ARCH="x64"



install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "$BUILD_ARCH" == "x64" ]]; then docker build -t zetavm/testing -f Dockerfile . ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "$BUILD_ARCH" == "x86" ]]; then docker build -t zetavm/testing -f Dockerfile-32 . ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -td --name zetavm -e CXX=$CXX zetavm/testing ; fi

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker exec zetavm ./configure ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker exec zetavm make -j4 test ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure && make -j4 && make test ; fi
