name: saga
version: 0.0.1
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  petitparser: any
  ui_utils:
    path: ../ui_utils
  liquid:
    git: git://github.com/mraleph/liquid.git
  observe: any
transformers:
- observe
- liquid
