language: cpp
os:
 - linux
sudo: false
dist: trusty
notifications:
 email:
  on_success: change # [always|never|change] # default: change
  on_failure: always # [always|never|change] # default: always

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lcov

script:
 - mkdir build
 - pushd build
 - cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DWITH_COVERAGE=on || exit 1
 - cmake --build . -- -j2 || exit 1
 - popd
 - cp build/lily .
 - cp build/pre-commit-tests .
 - ./pre-commit-tests || exit 1

after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
